<?php
/**
 * Implementation of hook_rules_event_info()
 */
function order_shipped_rules_event_info() {
  return array(
    'order_shipped_rule_event' => array(
      'label' => t('Order shipped event'),
      'module' => 'order_shipped',
      'group' => 'Cart' ,
      'variables' => array(
        'order' => array(
	    'type' => 'uc_order',
	    'label' => t('Order')
	    ),
      ),
    ),
  );
}